language: java
jdk:
    - oraclejdk8
after_success:
- python <(curl -s https://raw.githubusercontent.com/TouK/sputnik-ci/master/sputnik-ci.py)

env:
  global:
#  paste your api_key here
  - secure: a36a52e02ba7344fbcc56a9f332c4ada7400d4e34ff21f20b5e1cf817d24ebf4